# 使用指定的 Node.js 23.8 版本
FROM node:23.8 AS builder

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json
COPY package*.json ./

# 安裝依賴
RUN npm install --legacy-peer-deps

# 複製所有專案檔案
COPY . .

# 執行 Webpack 構建
RUN npm run build

# 開發階段（使用 webpack-dev-server）
FROM node:18.16.0
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3000
CMD ["npm", "run", "client:start"]