name: Deploy to Azure on Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install and Build Frontend
        run: |
          npm install
          npm run build

      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm install

      - name: Prepare Deployment Package
        run: |
          mkdir -p deploy
          cp -r build/* deploy/
          cp -r server/* deploy/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
      - run: az account show --debug
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MT716-REACT'  # 單一 App Service 名稱
          package: ./deploy