name: Deploy to Azure on Pull Request

on:
  pull_request:
    branches:
      - main  # 當 Pull Request 目標為 main 分支時觸發

permissions:
  id-token: write  # 允許工作流程獲取 OIDC ID 令牌
  contents: read   # 允許讀取代碼

jobs:
  build-frontend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install and Build Frontend
        run: |
          npm install --force
          npm run build --force
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: ./build

  build-backend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm install --force
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./server

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: ./build
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MT716-REACT'
          package: ./build

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: ./server
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MT716-NODE'
          package: ./server