name: Build and Deploy Frontend and Backend to Azure Web Apps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: windows-latest
    permissions:
      contents: read # 必要，用於 actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install and build frontend
        working-directory: ./client
        run: |
          npm install
          npm run build --if-present --force

      - name: Upload artifact for frontend deployment
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: ./client/build

  build-backend:
    runs-on: windows-latest
    permissions:
      contents: read # 必要，用於 actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install for backend
        working-directory: ./server
        run: |
          npm install

      - name: Upload artifact for backend deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./server

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # 必要，用於 Azure JWT
      contents: read  # 必要，用於 actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: ./build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_83F5F5404422484BA0D72D61CBC4C078 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDC4AFD9084D41FFBA9CBA27D5CCFB27 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20E5DC862CEF4FD0A6A856F98141D842 }}

      - name: Deploy to Azure Web App (Frontend)
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mt716react' # 前端 App Service 名稱
          slot-name: 'Production'
          package: ./build

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # 必要，用於 Azure JWT
      contents: read  # 必要，用於 actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: ./server

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_83F5F5404422484BA0D72D61CBC4C078 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDC4AFD9084D41FFBA9CBA27D5CCFB27 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20E5DC862CEF4FD0A6A856F98141D842 }}

      - name: Deploy to Azure Web App (Backend)
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mt716node' # 後端 App Service 名稱
          slot-name: 'Production'
          package: ./server